# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'twitterSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya','~> 11.0'  
  pod 'PKHUD', '~> 5.0'
  pod 'Kingfisher', '~>4.0'
  # Pods for twitterSearch

  target 'twitterSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'twitterSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
